packages:
  - configs/**
  - packages/ast/javascript
  - packages/ast/template
  - packages/blueprints
  - packages/cli
  - packages/ember-cli-string
  - packages/files
  - packages/json
  - packages/tests
