packages:
  - configs/**
  - packages/ast/javascript
  - packages/ast/template
  - packages/ast/template-tag
  - packages/blueprints
  - packages/cli
  - packages/ember
  - packages/files
  - packages/package-json
  - packages/tests
