allowBuilds:
  unrs-resolver: false

autoInstallPeers: false

minimumReleaseAge: 720

minimumReleaseAgeExclude:
  - "@ijlee2-frontend-configs/*"
  - "@oxc-minify/*"
  - "oxc-minify"

overrides:
  vite: ^8.1.3

packages:
  - "configs/**"
  - "docs"
  - "packages/ast/javascript"
  - "packages/ast/template"
  - "packages/ast/template-tag"
  - "packages/blueprints"
  - "packages/cli"
  - "packages/ember"
  - "packages/files"
  - "packages/package-json"
  - "packages/tests"
  - "packages/threads"

publicHoistPattern:
  - "*eslint*"
  - "*prettier*"
  - "*stylelint*"

resolvePeersFromWorkspaceRoot: false

verifyDepsBeforeRun: "warn"
