import { assert, normalizeFile } from '@codemod-utils/tests';

import { findTemplateTags } from '../../src/index.js';
import { testOnPosix } from '../helpers/index.js';

testOnPosix('find-template-tags > class (3)', function () {
  const oldFile = normalizeFile([
    `import Component from '@glimmer/component';`,
    `import { local } from 'embroider-css-modules';`,
    ``,
    `import styles from './example.css';`,
    ``,
    `const UserName = <template>`,
    `  <div`,
    `    class={{local styles "container" "highlight"}}`,
    `    data-test-field="😀😀a🎉🎉"`,
    `  >`,
    `    {{@user.name}}`,
    `  </div>`,
    `</template>;`,
    ``,
    `export default class MyComponent extends Component {`,
    `  get timestamp(): string {`,
    `    return 'yesterday';`,
    `  }`,
    ``,
    `  <template>`,
    `    <UserName @user={{@user}} />`,
    ``,
    `    <div class={{styles.container}} data-test-field="timestamp">`,
    `      {{this.timestamp}}`,
    ``,
    `  <p> 😀😀😀 Hello! 🎉🎉🎉`,
    `  </p>`,
    `    </div>`,
    `  </template>`,
    `}`,
  ]);

  const templateTags = findTemplateTags(oldFile);

  assert.deepStrictEqual(templateTags, [
    {
      contentRange: {
        endByte: 287,
        endChar: 275,
        endUtf16Codepoint: 279,
        startByte: 156,
        startChar: 156,
        startUtf16Codepoint: 156,
      },
      contents: normalizeFile([
        ``,
        `  <div`,
        `    class={{local styles "container" "highlight"}}`,
        `    data-test-field="😀😀a🎉🎉"`,
        `  >`,
        `    {{@user.name}}`,
        `  </div>`,
        ``,
      ]),
      endRange: {
        endByte: 298,
        endChar: 286,
        endUtf16Codepoint: 290,
        startByte: 287,
        startChar: 275,
        startUtf16Codepoint: 279,
      },
      range: {
        endByte: 298,
        endChar: 286,
        endUtf16Codepoint: 290,
        startByte: 146,
        startChar: 146,
        startUtf16Codepoint: 146,
      },
      startRange: {
        endByte: 156,
        endChar: 156,
        endUtf16Codepoint: 156,
        startByte: 146,
        startChar: 146,
        startUtf16Codepoint: 146,
      },
      tagName: 'template',
      type: 'expression',
    },
    {
      contentRange: {
        endByte: 608,
        endChar: 578,
        endUtf16Codepoint: 588,
        startByte: 423,
        startChar: 411,
        startUtf16Codepoint: 415,
      },
      contents: normalizeFile([
        ``,
        `    <UserName @user={{@user}} />`,
        ``,
        `    <div class={{styles.container}} data-test-field="timestamp">`,
        `      {{this.timestamp}}`,
        ``,
        `  <p> 😀😀😀 Hello! 🎉🎉🎉`,
        `  </p>`,
        `    </div>`,
        `  `,
      ]),
      endRange: {
        endByte: 619,
        endChar: 589,
        endUtf16Codepoint: 599,
        startByte: 608,
        startChar: 578,
        startUtf16Codepoint: 588,
      },
      range: {
        endByte: 619,
        endChar: 589,
        endUtf16Codepoint: 599,
        startByte: 413,
        startChar: 401,
        startUtf16Codepoint: 405,
      },
      startRange: {
        endByte: 423,
        endChar: 411,
        endUtf16Codepoint: 415,
        startByte: 413,
        startChar: 401,
        startUtf16Codepoint: 405,
      },
      tagName: 'template',
      type: 'class-member',
    },
  ]);
});
