import { assert, normalizeFile } from '@codemod-utils/tests';

import { findTemplateTags } from '../../src/index.js';
import { testOnPosix } from '../helpers/index.js';

testOnPosix('find-template-tags > template-only (4)', function () {
  const oldFile = normalizeFile([
    `import type { TOC } from '@ember/component/template-only';`,
    `import { hash } from '@ember/helper';`,
    `import { LinkTo } from '@ember/routing';`,
    `import { ContainerQuery, width } from 'ember-container-query';`,
    `import { t } from 'ember-intl';`,
    ``,
    `import type { Product } from '../../../utils/routes/products';`,
    `import styles from './card.css';`,
    `import ProductsProductImage from './image';`,
    ``,
    `export function formatPrice(price: number): string {`,
    `  return \`$\${price}\`;`,
    `}`,
    ``,
    `interface ProductsProductCardSignature {`,
    `  Args: {`,
    `    product: Product;`,
    `    redirectTo?: string;`,
    `  };`,
    `}`,
    ``,
    `const ProductsProductCardComponent: TOC<ProductsProductCardSignature> =`,
    `  <template>`,
    `    <ContainerQuery`,
    `      @features={{hash wide=(width min=320)}}`,
    `      @tagName="article"`,
    `      class={{styles.container}}`,
    `      data-test-product-card`,
    `    >`,
    `      <header class={{styles.header}}>`,
    `        <h2 class={{styles.name}} data-test-field="Name">`,
    `          {{@product.name}}`,
    `        </h2>`,
    `      </header>`,
    ``,
    `      <div class={{styles.image-container}}>`,
    `        <ProductsProductImage @src={{@product.imageUrl}} />`,
    `      </div>`,
    ``,
    `      <div class={{styles.body}}>`,
    `        <p class={{styles.description}} data-test-field="Short Description">`,
    `          {{@product.shortDescription}}`,
    `        </p>`,
    ``,
    `        <p class={{styles.price}} data-test-field="Price">`,
    `          {{formatPrice @product.price}}`,
    `        </p>`,
    `      </div>`,
    ``,
    `      <div class={{styles.actions}}>`,
    `        <LinkTo`,
    `          @model={{@product.id}}`,
    `          @route={{@redirectTo}}`,
    `          aria-label={{t`,
    `            "components.products.product.card.learn-more.aria-label"`,
    `            productName=@product.name`,
    `          }}`,
    `          class={{styles.link}}`,
    `          data-test-link="Learn More"`,
    `        >`,
    `          {{t "components.products.product.card.learn-more.label"}}`,
    `        </LinkTo>`,
    `      </div>`,
    `    </ContainerQuery>`,
    `  </template>;`,
    ``,
    `export default ProductsProductCardComponent;`,
    ``,
    `declare module '@glint/environment-ember-loose/registry' {`,
    `  export default interface Registry {`,
    `    'Products::Product::Card': typeof ProductsProductCardComponent;`,
    `    'products/product/card': typeof ProductsProductCardComponent;`,
    `  }`,
    `}`,
    ``,
  ]);

  const templateTags = findTemplateTags(oldFile);

  assert.deepStrictEqual(templateTags, [
    {
      contentRange: {
        endByte: 1837,
        endChar: 1837,
        endUtf16Codepoint: 1837,
        startByte: 643,
        startChar: 643,
        startUtf16Codepoint: 643,
      },
      contents: normalizeFile([
        ``,
        `    <ContainerQuery`,
        `      @features={{hash wide=(width min=320)}}`,
        `      @tagName="article"`,
        `      class={{styles.container}}`,
        `      data-test-product-card`,
        `    >`,
        `      <header class={{styles.header}}>`,
        `        <h2 class={{styles.name}} data-test-field="Name">`,
        `          {{@product.name}}`,
        `        </h2>`,
        `      </header>`,
        ``,
        `      <div class={{styles.image-container}}>`,
        `        <ProductsProductImage @src={{@product.imageUrl}} />`,
        `      </div>`,
        ``,
        `      <div class={{styles.body}}>`,
        `        <p class={{styles.description}} data-test-field="Short Description">`,
        `          {{@product.shortDescription}}`,
        `        </p>`,
        ``,
        `        <p class={{styles.price}} data-test-field="Price">`,
        `          {{formatPrice @product.price}}`,
        `        </p>`,
        `      </div>`,
        ``,
        `      <div class={{styles.actions}}>`,
        `        <LinkTo`,
        `          @model={{@product.id}}`,
        `          @route={{@redirectTo}}`,
        `          aria-label={{t`,
        `            "components.products.product.card.learn-more.aria-label"`,
        `            productName=@product.name`,
        `          }}`,
        `          class={{styles.link}}`,
        `          data-test-link="Learn More"`,
        `        >`,
        `          {{t "components.products.product.card.learn-more.label"}}`,
        `        </LinkTo>`,
        `      </div>`,
        `    </ContainerQuery>`,
        `  `,
      ]),
      endRange: {
        endByte: 1848,
        endChar: 1848,
        endUtf16Codepoint: 1848,
        startByte: 1837,
        startChar: 1837,
        startUtf16Codepoint: 1837,
      },
      range: {
        endByte: 1848,
        endChar: 1848,
        endUtf16Codepoint: 1848,
        startByte: 633,
        startChar: 633,
        startUtf16Codepoint: 633,
      },
      startRange: {
        endByte: 643,
        endChar: 643,
        endUtf16Codepoint: 643,
        startByte: 633,
        startChar: 633,
        startUtf16Codepoint: 633,
      },
      tagName: 'template',
      type: 'expression',
    },
  ]);
});
