import { assert, test } from '@codemod-utils/tests';

import { replaceTemplateTag } from '../../src/index.js';

test('replace-template-tag > rendering test (2)', function () {
  const oldFile = [
    `import Service from '@ember/service';`,
    `import { type Registry as Services, service } from '@ember/service';`,
    `import { render, type TestContext } from '@ember/test-helpers';`,
    `import { setupRenderingTest } from 'ember-qunit';`,
    `import Example1 from 'my-app/components/example-1';`,
    `import { module, test } from 'qunit';`,
    ``,
    `module('Integration | Component | example-1', function (hooks) {`,
    `  setupRenderingTest(hooks);`,
    ``,
    `  hooks.beforeEach(function (assert) {`,
    `    this.owner.register(`,
    `      'service:example-1/business-logic',`,
    `      class Example1BusinessLogic extends Service {`,
    `        @service declare intl: Services['intl'];`,
    ``,
    `        get timestamp(): string {`,
    `          return '2025-01-01';`,
    `        }`,
    `      },`,
    `    );`,
    `  });`,
    ``,
    `  test('it renders', async function (assert) {`,
    `    await render(<template><Example1 /></template>);`,
    ``,
    `    assert.ok(true);`,
    `  });`,
    ``,
    `  test('We can pass styles', async function (this: TestContext, assert) {`,
    `    await render(`,
    `      <template>`,
    `        <Example1 class="my-style" />`,
    `      </template>,`,
    `    );`,
    ``,
    `    assert.ok(true);`,
    `  });`,
    `});`,
    ``,
  ].join('\n');

  const newFile = replaceTemplateTag(oldFile, {
    code: '<template>New contents</template>',
    range: {
      endByte: 1006,
      endChar: 1006,
      startByte: 940,
      startChar: 940,
    },
  });

  assert.strictEqual(
    newFile,
    [
      `import Service from '@ember/service';`,
      `import { type Registry as Services, service } from '@ember/service';`,
      `import { render, type TestContext } from '@ember/test-helpers';`,
      `import { setupRenderingTest } from 'ember-qunit';`,
      `import Example1 from 'my-app/components/example-1';`,
      `import { module, test } from 'qunit';`,
      ``,
      `module('Integration | Component | example-1', function (hooks) {`,
      `  setupRenderingTest(hooks);`,
      ``,
      `  hooks.beforeEach(function (assert) {`,
      `    this.owner.register(`,
      `      'service:example-1/business-logic',`,
      `      class Example1BusinessLogic extends Service {`,
      `        @service declare intl: Services['intl'];`,
      ``,
      `        get timestamp(): string {`,
      `          return '2025-01-01';`,
      `        }`,
      `      },`,
      `    );`,
      `  });`,
      ``,
      `  test('it renders', async function (assert) {`,
      `    await render(<template><Example1 /></template>);`,
      ``,
      `    assert.ok(true);`,
      `  });`,
      ``,
      `  test('We can pass styles', async function (this: TestContext, assert) {`,
      `    await render(`,
      `      <template>New contents</template>,`,
      `    );`,
      ``,
      `    assert.ok(true);`,
      `  });`,
      `});`,
      ``,
    ].join('\n'),
  );
});
