import { assert, test } from '@codemod-utils/tests';

import { toTemplateTag } from '../../src/index.js';

test('to-template-tag > rendering test (2)', function () {
  const oldFile = [
    `import { template as template_fd9b2463e5f141cfb5666b64daa1f11a } from "@ember/template-compiler";`,
    `import Service from '@ember/service';`,
    `import { type Registry as Services, service } from '@ember/service';`,
    `import { render, type TestContext } from '@ember/test-helpers';`,
    `import { setupRenderingTest } from 'ember-qunit';`,
    `import Example1 from 'my-app/components/example-1';`,
    `import { module, test } from 'qunit';`,
    ``,
    `module('Integration | Component | example-1', function (hooks) {`,
    `  setupRenderingTest(hooks);`,
    ``,
    `  hooks.beforeEach(function (assert) {`,
    `    this.owner.register(`,
    `      'service:example-1/business-logic',`,
    `      class Example1BusinessLogic extends Service {`,
    `        @service declare intl: Services['intl'];`,
    ``,
    `        get timestamp(): string {`,
    `          return '2025-01-01';`,
    `        }`,
    `      },`,
    `    );`,
    `  });`,
    ``,
    `  test('it renders', async function (assert) {`,
    `    await render(template_fd9b2463e5f141cfb5666b64daa1f11a(\`<Example1 />\`, {`,
    `    eval () {`,
    `        return eval(arguments[0]);`,
    `    }`,
    `}));`,
    ``,
    `    assert.ok(true);`,
    `  });`,
    ``,
    `  test('We can pass styles', async function (this: TestContext, assert) {`,
    `    await render(`,
    `      template_fd9b2463e5f141cfb5666b64daa1f11a(\``,
    `<Example1 class="my-style" />`,
    `\`, {`,
    `    eval () {`,
    `        return eval(arguments[0]);`,
    `    }`,
    `}),`,
    `    );`,
    ``,
    `    assert.ok(true);`,
    `  });`,
    `});`,
    ``,
  ].join('\n');

  const newFile = toTemplateTag(oldFile);

  assert.strictEqual(
    newFile,
    [
      `import Service from '@ember/service';`,
      `import { type Registry as Services, service } from '@ember/service';`,
      `import { render, type TestContext } from '@ember/test-helpers';`,
      `import { setupRenderingTest } from 'ember-qunit';`,
      `import Example1 from 'my-app/components/example-1';`,
      `import { module, test } from 'qunit';`,
      ``,
      `module('Integration | Component | example-1', function (hooks) {`,
      `  setupRenderingTest(hooks);`,
      ``,
      `  hooks.beforeEach(function (assert) {`,
      `    this.owner.register(`,
      `      'service:example-1/business-logic',`,
      `      class Example1BusinessLogic extends Service {`,
      `        @service declare intl: Services['intl'];`,
      ``,
      `        get timestamp(): string {`,
      `          return '2025-01-01';`,
      `        }`,
      `      },`,
      `    );`,
      `  });`,
      ``,
      `  test('it renders', async function (assert) {`,
      `    await render(<template><Example1 /></template>);`,
      ``,
      `    assert.ok(true);`,
      `  });`,
      ``,
      `  test('We can pass styles', async function (this: TestContext, assert) {`,
      `    await render(<template>`,
      `    <Example1 class="my-style" />`,
      `    </template>);`,
      ``,
      `    assert.ok(true);`,
      `  });`,
      `});`,
      ``,
    ].join('\n'),
  );
});
